/*CREATE TABLE Users (
	USERID int IDENTITY (1,1) PRIMARY KEY ,
	FIRSTNAME varchar(255) NOT NULL,
	LASTNAME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	CONSTRAINT UC_USERNAME UNIQUE(FIRSTNAME, LASTNAME),
	CONSTRAINT UC_USERID UNIQUE(USERID)
);*/
/*
CREATE TABLE Customers (
	CUSTOMERID int IDENTITY(1,1) PRIMARY KEY,
	USERID int NOT NULL,
	COMPANYNAME varchar(255) NOT NULL
);*/

/*ALTER TABLE Customers
ADD CONSTRAINT FK_USERID
FOREIGN KEY (USERID) REFERENCES Users(USERID);
*/
CREATE TABLE Rentals (
	RENTID int IDENTITY(1,1) PRIMARY KEY,
	CARID int NOT NULL,
	CUSTOMERID int NOT NULL,
	RENTDATE date NOT NULL,
	RETURNDATE date
);

ALTER TABLE Rentals
ADD CONSTRAINT FK_CARID
FOREIGN KEY (CARID) REFERENCES Cars(CARID);

ALTER TABLE Rentals
ADD CONSTRAINT FK_CUSTOMERID
FOREIGN KEY (CUSTOMERID) REFERENCES Customers(CUSTOMERID);
